### ISSUE TITLE
IntegerParameter value should have type int

### ISSUE THREAD

**Issue by magland** [flatironinstitute/mlprocessors#1]
I would expect that IntegerParameter value would have type integer, but it seems to have type float.

For example

```
foo=IntegerParameter("some description",optional=True,default=20)
```

Then in the run function, `self.foo` appears to have type float.

**Comment by wysota** [comment]
How did you check that? For me it seems it is an int:

```
#!/usr/bin/env python3

from mlprocessors import Processor, IntegerParameter
from mlprocessors.registry import registry


class TestProc(Processor):
  p1 = IntegerParameter()
  def run(self):
    print(isinstance(self.p1, int))

registry.register(TestProc)


if __name__=="__main__":
  import sys
  registry.process(sys.argv)
```

$ ./test_int.py TestProc --p1 1
True

**Comment by wysota** [comment]
Closing. If you can reproduce the issue, feel free to reopen.
